package-lock.json, package.json, src/components/projectPage.tsx, src/components/subTaskColumn.tsx, src/index.tsx
The impossible has been achieved
=> Bootstrap + tslint 

src/components/applicationConfig.ts, src/components/projectColumn.tsx, src/components/projectPage.tsx, src/components/subTaskButton.tsx, src/components/subTaskColumn.tsx, src/components/subtaskType.ts, src/components/taskView.tsx, tsconfig.json
Github refused to append my new commits to the old PR so here's a new one with the new commits
=> Github was mean so I had to reopen this

src/components/assignedDropdown.tsx, src/components/landProjCol.tsx, src/components/mainPage.tsx, src/components/navBar.tsx, src/components/projLanding.tsx, src/components/projectColumn.tsx, src/components/projectPage.tsx, src/components/subTaskButton.tsx, src/components/subTaskColumn.tsx
This PR does a little bit of re-working of the previous PR and implements selecting a project from the landing page.
=> Show Selected Project From Landing Page

src/components/newProjectButton.tsx, src/components/newSubTaskButton.tsx
Quick fix to make sure all data fields are filled when posting to the database.
=> Fix Post Data

src/components/assignedDropdown.tsx, src/components/projectPage.tsx, src/components/statusDropdown.tsx, src/components/taskView.tsx
So on top of the original goal of integrating updating task information to the database, this accomplishes a few other things, including:
- allows the user to change the name of tasks (it's a textbox now)
- prevents setting a task to "complete" if its subtasks are not set to "complete"
- fixes components of a task not visually updating when new tasks are selected
I know we aren't supposed to do pull requests that involve _multiple_ things being done but this was originally supposed to just be updating all info for a task to the database, but in order to achieve _that_ I had to change statusDropdown and assignedDropdown to have them send their values to TaskView, _then_ I realized the task I was doing also included preventing the user from changing a task to "completed" if its subtasks …
=> Integrates updating tasks to database, and more

src/components/landProjCol.tsx, src/components/mainPage.tsx, src/components/newProjectButton.tsx, src/components/newSubTaskButton.tsx, src/components/projLanding.tsx, src/components/projectColumn.tsx, src/components/projectPage.tsx, src/components/subTaskColumn.tsx, src/components/taskView.tsx, src/components/userHeaderHttpRequest.ts, src/components/userInfo.ts
This affects all calls to the API. I double-checked things, but please look at this review very carefully.
=> Pass user info into each request.

src/components/assignedDropdown.tsx, src/components/landProjCol.tsx, src/components/mainPage.tsx, src/components/navBar.tsx, src/components/newProjectButton.tsx, src/components/newSubTaskButton.tsx, src/components/projLanding.tsx, src/components/projectColumn.tsx, src/components/projectPage.tsx, src/components/statusDropdown.tsx, src/components/subTaskColumn.tsx, src/components/taskTags.tsx, src/components/taskView.tsx, src/components/userHeaderHttpRequest.ts, src/components/userInfo.ts, src/index.tsx
=> Format all TS files.

src/components/landProjCol.tsx, src/components/newProjectButton.tsx, src/components/newSubTaskButton.tsx, src/components/projectColumn.tsx, src/components/projectPage.tsx, src/components/retryableFetch.ts, src/components/subTaskColumn.tsx, src/components/taskView.tsx
Implement static function to retry all fetch calls up to 4 additional times.
=> Retry all fetches up to 4 additional times.

src/components/progressBar.tsx, src/components/projectPage.tsx, src/components/statusDropdown.tsx, src/components/taskView.tsx
What I thought would take 30 minutes instead took 3 days.
The solution to calculating the progress is disastrously heavy handed and confusing. Honestly, good luck figuring out the mess that I had to create to make this work.
This is very heavy on fetches and might be able to be reduced, but I don't think without some major reworks this could be improved much.
Anyhow, it doesn't work as well as I'd like. For one, dependent on the speed of the database, the progress on the left may or may not update. Run the db locally and it works like a charm, otherwise your performance will vary. Please test this thoroughly and look for bugs, I expect some to exist.
=> Fix Task Progress

package.json
=> Fix node deps.

src/components/projectPage.tsx, src/components/taskView.tsx
Fixes the bugs and crashes related to the progress when a task is deleted. Also contains a quick fix where the project name was not being updated in the column view.
=> Update Progress When a Task is Deleted

src/components/mainPage.tsx, src/components/projectPage.tsx, src/components/statTab.tsx
Add api integration with the stats page.
=> Fixed login issue and added stats integration.

src/components/applicationConfig.ts, src/components/historyTab.tsx, src/components/projectPage.tsx
=> History tab integration

src/components/landProjCol.tsx, src/components/loadingPage.tsx, src/components/newProjectButton.tsx, src/components/newSubTaskButton.tsx, src/components/projLanding.tsx, src/components/projectColumn.tsx, src/components/projectPage.tsx, src/components/subTaskColumn.tsx
Thanks to some weird rebases this is all one commit, sorry.
Adds a bunch of loading and error states to show the user in a non-abrupt fashion that the app isn't read yet.
=> Style Loading and Error States

src/components/applicationConfig.ts, src/components/applicationEntry.tsx, src/components/homePage.tsx, src/components/mainLanding.tsx, src/components/mainPage.tsx, src/components/navBar.tsx, src/components/newProjectButton.tsx, src/components/projLanding.tsx, src/components/signInButton.tsx, src/index.tsx
=> Google Auth

src/components/assignedDropdown.tsx, src/components/projectPage.tsx, src/components/taskType.ts, src/components/taskView.tsx
=> Implement AssignedTo Select box integration.

src/components/shareUsers.tsx, src/components/taskView.tsx
Right now, we are not tracking the user's name in the DB. It seems like too much work at this point to make a change that large, so I'm doing everything based on the email.
=> Add ability to view and add collaborators.

src/components/homePage.tsx
Quick fix that resolves being unable to create a new project after google auth
=> fix porject creation bug

src/components/mainLanding.tsx, src/components/navBar.tsx
- add picture to main landing
- remove account from Navbar
=> Quick Changes

src/components/projectPage.tsx
These bugs got in the way of my presentation and for that they had to be punished.
I fixed the issue where the name of a parent task would suddenly change.
I fixed a crash related to making a new subtask.
=> fix name issue and crash
